//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vertragsmanagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.Contracts1 = new HashSet<Contract>();
            this.CostCentreDivides = new HashSet<CostCentreDivide>();
            this.Documents = new HashSet<Document>();
            this.Tasks = new HashSet<Task>();
            this.OtherFeatures = new HashSet<OtherFeature>();
            this.Users = new HashSet<User>();
            this.Users1 = new HashSet<User>();
        }
    
        public int intID { get; set; }
        public Nullable<int> extID { get; set; }
        public string titel { get; set; }
        public Nullable<decimal> contractValue { get; set; }
        public Nullable<decimal> contractCosts { get; set; }
        public Nullable<int> paymentIntervall { get; set; }
        public Nullable<int> noticePeriod { get; set; }
        public Nullable<int> earliestNoticePeriod { get; set; }
        public Nullable<int> contractExtension { get; set; }
        public Nullable<decimal> valueTax { get; set; }
        public string remark { get; set; }
        public int state { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> subcategoryID { get; set; }
        public Nullable<int> speciesID { get; set; }
        public Nullable<int> signerID { get; set; }
        public Nullable<int> personInChargeID { get; set; }
        public Nullable<int> mappedDepartmentID { get; set; }
        public Nullable<int> observingDepartmentID { get; set; }
        public string partnerID { get; set; }
        public Nullable<System.DateTime> paymentBegin { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> noticeDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.DateTime> remindingDate { get; set; }
        public Nullable<System.DateTime> escalationDate { get; set; }
        public bool escalated { get; set; }
        public bool reminded { get; set; }
        public bool noticeReminded { get; set; }
        public string locality { get; set; }
        public Nullable<int> partnerIs { get; set; }
        public Nullable<int> frameworkContractID { get; set; }
        public bool isframeworkContract { get; set; }
    
        public virtual ContractCategory ContractCategory { get; set; }
        public virtual ContractPartner ContractPartner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts1 { get; set; }
        public virtual Contract Contract1 { get; set; }
        public virtual ContractSpecy ContractSpecy { get; set; }
        public virtual ContractSubcategory ContractSubcategory { get; set; }
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostCentreDivide> CostCentreDivides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherFeature> OtherFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users1 { get; set; }
    }
}
