//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vertragsmanagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCentre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CostCentre()
        {
            this.CostCentreDivides = new HashSet<CostCentreDivide>();
        }
    
        public int ID { get; set; }
        public string describtion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostCentreDivide> CostCentreDivides { get; set; }
    }
}
