//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vertragsmanagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string link { get; set; }
        public Nullable<int> Contract_intID { get; set; }
        public string category { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
